### ISSUE TITLE
Task 11 (clients display)

### ISSUE THREAD

**Issue by pmvald** [Appers-lab/sss-theme#8]
We want to make a partner logos list similar to the page "clients.html" in the canvas theme (the first one with 6 columns should be good). 

Create a new file _partners.scss in "styles" folder and define the class "s-partner-logos" there. Use BEM guidelines as described the design guide. For the html part, you can use layer 0 classes (layouts.scss). So your html would look like:

```html
<article class="row s-partner-logos">

  <div class="col-2">
     <img src="logo1">
  </div>

  <div class="col-2">
     <img src="logo2">
  </div>

  <div class="col-2">
     <img src="logo3">
  </div>

</article>
```

You can create a new folder /tasks/task-011 and test your design in an html in that folder along with the following list of partner logos:

[Partner_logos.zip](https://github.com/Appers-lab/billihomes-frontend/files/6586302/Partner_logos.zip)

**Comment by navjot-chahal** [comment]
@pmvald I am stuck on this issue. Can you please help?
![image](https://user-images.githubusercontent.com/60498899/121927692-3482b580-ccf4-11eb-8ccd-198e53b4b61d.png)

**Comment by navjot-chahal** [comment]
"I was under the impression that the grid should be open at the border and it must implement. So I masked the outer grid section similar to what "client.html" does in the canvas theme reference.

I tried to use the nth-child selector similar to what you mentioned with borders on the right and the bottom and no right borders for every (6n+6) child (right-most grid item). But being a bootstrap grid the elements inside are cascaded in a row-based flexbox. So there are no special attributes present in the last row logos that we can use in the nth-child selector to have its bottom-border removed.

I assume that we wanted this layout to work for any number of logos, so that's why my code was very long previously. But for this pull in order to use nth-child, I had to hard code the "border-bottom: none" for the last four logos. This is not what I initially thought, as this works for 16 logos (given). Please advise if this is acceptable or if there is a better way to implement this with nth-child.

PS: Thanks for your patience."

@pmvald - Can you please guide/advise me on this?
